### ISSUE TITLE
Implement `SetTargetFPS()`

### ISSUE THREAD

**Issue by ritchielrez** [tsoding/zozlib.js#19]
By default, `window.requestAnimationFrame()` does not support a custom FPS lock, and it is probably better to leave it as it is. But implementing a way to control the **updates per second rather than the FPS** is something that can be done.  I am not exactly sure what is the exact right way to do this, but here's an example I found on the internet and how I am implementing this in my game currently:

```typescript
const fps = 60;
const frameTime = 1000/fps;
let previousTime = 0.0;
let currentTime = 0.0;
let deltaTime = 0.0;

function gameLoop(timeStamp: number) {
    if (isGameRunning === true) {
        currentTime = timeStamp;
        if(previousTime === 0) {
            previousTime = currentTime;
        }
        deltaTime = currentTime - previousTime;
        if(deltaTime >= frameTime) {
            previousTime = currentTime - (deltaTime % frameTime);
            update();
        }
        draw();
        window.requestAnimationFrame(gameLoop);
}

window.requestAnimationFrame(gameLoop);
```

**Comment by ArjixWasTaken** [comment]
Already did it in a closed PR, but Mr Tsoding introduced a conflict (bc of the rewrite) so my PR was closed.
I don't really plan to re-open it as I've lost interest (the PR had no reason to close, I could push new commits there but alas)

If you want, feel free to get some inspiration from my code

https://github.com/tsoding/zozlib.js/pull/4

**Comment by ritchielrez** [comment]
@ArjixWasTaken I also considered the use of `setTimeout` here, but it generally not recommend to use for games. Because the browser has its own browser repaint loop, `requestAnimationFrame` makes sure to call draw functions only when the browser repaint is occurring.
